from triangulum.utils.enums import ChatRoomType

CHAT_ROOM_GLOBAL = str(ChatRoomType.PUBLIC.value) + '.global'
CHAT_ROOM_BEGINNER = str(ChatRoomType.PUBLIC.value) + '.beginner'

TROOPS_SECOND_TARGET_CATAPULTS = 20
TROOPS_MAX_LEVEL = 20

BUILDING_QUEUE_FREE_MASTER_BUILDER_SLOTS = 1
BUILDING_QUEUE_MASTER_BUILDER_SLOTS = 4

BUILDING_MAX_LEVEL = 20
BUILDING_WW_MAX_LEVEL = 100
BUILDING_MIN_FREE_CROP_AVAILABLE = 2
BUILDING_PREMIUM_LOCATIONS = [42, 43]
BUILDING_RALLY_POINT_LOCATION = 32

FARMLIST_ENTRY_PREVENT_UPDATE_WITHOUT_FIRST_FILL = True

GROUP_INVITATION_COLLECTION_FOR_GROUP = 'group'
HERO_ITEM_PREVENT_UPDATE_WITHOUT_FIRST_FILL = True

# Limits the use of the npc trader feature by the amount of traded resources
PREMIUM_FEATURE_NPC_TRADER_INSIGNIFICANCE_LIMIT = 5

QUEST_DAILY_QUESTS_NUMBER = 3
QUEST_DAILY_CONDITIONAL_OPEN_PREMIUM_MENU = 10015

REPORT_REPORTS_PER_PAGE = 10
